#---------------------------------#
#         Build Environment       #
#---------------------------------#
image: Visual Studio 2017

#---------------------------------#
#      Environment Variables      #
#---------------------------------#
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

#---------------------------------#
#        Cake Bootstrapper        #
#---------------------------------#
build_script:
  - ps: .\build.ps1 -Target AppVeyor

#---------------------------------#
#         Test and Deploy         #
#---------------------------------#
test: off # tests are handled by cake script
deploy: off # deploy are handled by cake script

#---------------------------------#
#        Branches to build        #
#---------------------------------#
branches:
  # Whitelist
  only:
    - master
    - /release/.*/
    - /hotfix/.*/

#---------------------------------#
#           Build Cache           #
#---------------------------------#
cache:
- Source\packages -> Source\**\packages.config
- tools -> recipe.cake
