language: csharp

#---------------------------------#
#         Build Environment       #
#---------------------------------#
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode9.4

#---------------------------------#
#      Environment Variables      #
#---------------------------------#
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - DOTNET_CLI_TELEMETRY_OPTOUT=1

#---------------------------------#
#        Build Dependencies       #
#---------------------------------#
mono: latest
dotnet: 2.1.300

#---------------------------------#
#        Cake Bootstrapper        #
#---------------------------------#
script:
  - ./build.sh -v diagnostic

#---------------------------------#
#           Build Cache           #
#---------------------------------#
cache:
  directories:
    - packages
    - tools